"""Initial database schema

Revision ID: 35da9af69f87
Revises: 
Create Date: 2026-01-27 00:05:31.579492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35da9af69f87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('doc_type', sa.Enum('PDF', 'WEB', 'TEXT', 'MARKDOWN', 'API', name='documenttype', schema='app'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('status', sa.Enum('PENDING', 'INDEXED', 'ERROR', name='documentstatus', schema='app'), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False, comment='Author, tags, category, etc.'),
    sa.Column('indexed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_documents_created_at'), 'documents', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_documents_doc_type'), 'documents', ['doc_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_documents_status'), 'documents', ['status'], unique=False, schema='app')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', schema='app'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_created_at'), 'users', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='conversationstatus', schema='app'), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False, comment='Additional data: language, tags, score, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_conversations_created_at'), 'conversations', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_status'), 'conversations', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='app')
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position in document'),
    sa.Column('embedding_id', sa.Integer(), nullable=True, comment='Reference to FAISS index'),
    sa.Column('meta_data', sa.JSON(), nullable=False, comment='Page number, section, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='app')
    op.create_table('actions',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('EMAIL', 'CRM', 'TICKET', 'SCORING', 'NOTIFICATION', name='actiontype', schema='app'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='actionstatus', schema='app'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Action input data'),
    sa.Column('result', sa.JSON(), nullable=False, comment='Action output data'),
    sa.Column('executed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_actions_action_type'), 'actions', ['action_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_actions_conversation_id'), 'actions', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_actions_created_at'), 'actions', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_actions_status'), 'actions', ['status'], unique=False, schema='app')
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', schema='app'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False, comment='Sources, confidence, tokens, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_messages_created_at'), 'messages', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_messages_role'), 'messages', ['role'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_messages_role'), table_name='messages', schema='app')
    op.drop_index(op.f('ix_app_messages_created_at'), table_name='messages', schema='app')
    op.drop_index(op.f('ix_app_messages_conversation_id'), table_name='messages', schema='app')
    op.drop_table('messages', schema='app')
    op.drop_index(op.f('ix_app_actions_status'), table_name='actions', schema='app')
    op.drop_index(op.f('ix_app_actions_created_at'), table_name='actions', schema='app')
    op.drop_index(op.f('ix_app_actions_conversation_id'), table_name='actions', schema='app')
    op.drop_index(op.f('ix_app_actions_action_type'), table_name='actions', schema='app')
    op.drop_table('actions', schema='app')
    op.drop_index(op.f('ix_app_document_chunks_document_id'), table_name='document_chunks', schema='app')
    op.drop_index(op.f('ix_app_document_chunks_created_at'), table_name='document_chunks', schema='app')
    op.drop_table('document_chunks', schema='app')
    op.drop_index(op.f('ix_app_conversations_user_id'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_status'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_created_at'), table_name='conversations', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_created_at'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_index(op.f('ix_app_documents_status'), table_name='documents', schema='app')
    op.drop_index(op.f('ix_app_documents_doc_type'), table_name='documents', schema='app')
    op.drop_index(op.f('ix_app_documents_created_at'), table_name='documents', schema='app')
    op.drop_table('documents', schema='app')
    # ### end Alembic commands ###
