"""Add RAG fields to conversations and messages

Revision ID: 7be1f31a74fe
Revises: cac39199cddc
Create Date: 2026-01-30 22:27:17.140231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be1f31a74fe'
down_revision: Union[str, None] = 'cac39199cddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.knowledge_bases (
            id UUID PRIMARY KEY,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            name VARCHAR(200) NOT NULL,
            description TEXT,
            user_id UUID NOT NULL REFERENCES app.users(id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app.documents_rag (
            id UUID PRIMARY KEY,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            filename VARCHAR(255) NOT NULL,
            file_path VARCHAR(1000) NOT NULL,
            file_type VARCHAR(50) NOT NULL,
            file_size INTEGER,
            chunk_count INTEGER,
            knowledge_base_id UUID NOT NULL REFERENCES app.knowledge_bases(id) ON DELETE CASCADE,
            user_id UUID NOT NULL REFERENCES app.users(id) ON DELETE CASCADE
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_knowledge_bases_created_at ON app.knowledge_bases (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_knowledge_bases_user_id ON app.knowledge_bases (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_documents_rag_created_at ON app.documents_rag (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_documents_rag_knowledge_base_id ON app.documents_rag (knowledge_base_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_app_documents_rag_user_id ON app.documents_rag (user_id)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('knowledge_base_id', sa.UUID(), nullable=True), schema='app')
    op.create_index(op.f('ix_app_conversations_knowledge_base_id'), 'conversations', ['knowledge_base_id'], unique=False, schema='app')
    op.create_foreign_key(None, 'conversations', 'knowledge_bases', ['knowledge_base_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.add_column('messages', sa.Column('sources', sa.JSON(), nullable=True, comment='RAG source documents used'), schema='app')
    op.add_column('messages', sa.Column('rag_used', sa.Boolean(), nullable=False, comment='RAG logic indicator'), schema='app')
    op.add_column('messages', sa.Column('retrieval_score', sa.Float(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'retrieval_score', schema='app')
    op.drop_column('messages', 'rag_used', schema='app')
    op.drop_column('messages', 'sources', schema='app')
    op.drop_constraint(None, 'conversations', schema='app', type_='foreignkey')
    op.drop_index(op.f('ix_app_conversations_knowledge_base_id'), table_name='conversations', schema='app')
    op.drop_column('conversations', 'knowledge_base_id', schema='app')
    # ### end Alembic commands ###
